name: React app deployement

on:
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react app to github pages
      steps:
        - run : npm i -f
          shell: bash
        - run : npm ci
          shell: bash
        - run : npm run build
          shell: bash
        - run : git config user.name github-actions
          shell: bash
        - run : git config user.email github-actions@github.com
          shell: bash
        - run : git --work-tree build add --all
          shell: bash
        - run : git commit -m "Automatic Deploy action run by github-actions"
          shell: bash
        - run : git push origin HEAD:gh-pages --force
          shell: bash